### ISSUE TITLE
Update your Assessment question answers

### ISSUE THREAD

**Issue by BavariaBlue** [BavariaBlue/samm#19]
In the newest version of the Excel file, all recently added assessment questions lack of a structured answering. 

I.e: LSC 1: 
"Does your organization have an open discussion about organizational deficiencies, human faults and Intentional activities?"
Current answer: No - Yes, we did it once - we do it every few years - we do it at least annually 

--> Here, the answers to the question clearly don't match.

Please rely on the answer matrix (see attached png) to find appropriate answers to your question in your Security Practice. 
<img width="465" alt="Bildschirmfoto 2019-07-29 um 10 05 57" src="https://user-images.githubusercontent.com/16705095/62443656-be0de780-b75b-11e9-922c-e544144b5baf.png">
If no answer out of the matrix suits your case, introduce a new question - but hold on to the original answers whenever possible.

In order to simplify the process, you do not have to edit the Excel file, rather send me a text note.

Current Excel version:
https://github.com/BavariaBlue/samm/blob/master/Supporting%20Resources/v1.5/MarkDown/Draft/SAMM_Assessment_Toolbox_v1.5.1.xlsx

Current .md file:
https://github.com/BavariaBlue/samm/blob/master/Supporting%20Resources/v1.5/MarkDown/SAMM-1.5.1.md

A text note sample is attached to the issue.

**Comment by BavariaBlue** [comment]
[guidance.txt](https://github.com/BavariaBlue/samm/files/3466231/guidance.txt)

**Comment by KatjaAuernhammer** [comment]
Answers for Questions Lifecycle Security Design:
LCSD 1
Do projects execute risk analysis (e.g., in regard to (A)SIL)?
Rephrase to "Do project teams execute risk analysis (e.g., in regard to (A)SIL)?" or "Are risk analyses (e.g., in regard to (A)SIL) executed for projects?"
Answers C: Yes, a small percentage, Yes at least half of them are/do,...

Are identified attack patterns documented in a reusable catalog?
Answers C: Yes, a small percentage, Yes at least half of them are/do,...

LCSD2
Are penetration tests planned and categorized for all products?
Answers C: Yes, a small percentage, Yes at least half of them are/do,...

How often are external security reports reviewed?
Rephrase to "Are external security reports reviewed?"
Answers D: Yes, we did it once, Yes we do it every year,...

Is special staff trained or are external certified testers employed? 
Answers C: Yes, a small percentage, Yes at least half of them are/do,...

Is the security of external SW and HW components guaranteed?
Answers C: Yes, a small percentage, Yes at least half of them are/do,...

LCSD3
Can products be tested hardware independently?
Answers C: Yes, a small percentage, Yes at least half of them are/do,...

Can products be updated subsequently after rollout?
Answers C: Yes, a small percentage, Yes at least half of them are/do,... 

Can results from penetration tests be reused?
Answers C: Yes, a small percentage, Yes at least half of them are/do,...

Is security already implemented into the lifecycle?
Answers G: Yes, localized to business areas, Yes, across the organization,...
Or rephrase to:
Are security practices already implemented into the lifecycle?
Answers C: Yes, a small percentage, Yes at least half of them are/do,...

What do you think, @TabeaSpahn ?

@BavariaBlue Could you please update the shortcuts in the Excel sheet as well? It's LCSD instead of LSD  :) Thank you!

2019-08-06 - Updated: Added rest of questions. 

~ Katja

**Comment by BavariaBlue** [comment]
@TabeaSpahn 
Did you review all your Design questions? (10 questions)?
I will update the shortcuts.

**Comment by ebroecker** [comment]
Answers for LSM
-------------------

## LSM:

Q1: Does your organization gather information about new vulnerability issues?
A: Answer D (Yes, wi did it once, ...) 

Q2: Are vulnerability issues filtered to dedicated project, used hardware and software stacks?
A: Answer E (No It's not applicable, ...)

Q3: Are there project teams after final (serial) release responsible for these issues?
A: Answer B (Yes, some of them...)

-------------------

## LSM2:

Q1: Is your penetration test continuously developed?
A: Answer E (No, it's not applicable...)

Q2:Do you assure that penetration tests are executed for every released hardware/software combination?
A: Answer E (No, it's not applicable...)

Q3:Does your company collect and archive all results of these penetration tests?
A: Answer C (Yes, a small percentage, ...)

-------------------

## LSM3:

Q1:Does your company know how to contact the end users of your devices?
A: Answer B (Yes, some of them...)

Q2:Does your company have a process which defines the propagation of security vulnerabilities to your customers?
A: Answer G (Yes, localized ...)

Q3:Do your project teams provide a security degradation guidance model?
A: Answer F (Yes, teams write/run their own)

Q4: Does your company have a process which defines the propagation of security updates to end users?
A: Answer F (Yes, teams write ther own, ...)

**Comment by BavariaBlue** [comment]
new branch created on remote:

https://github.com/BavariaBlue/samm/tree/assessmentAnswers

Updated Design, Testing and monitoring + created newest PDF file
Missing: Culture
